# Desafio Entregável - Turma 40120

Grupo: André, Camila

# Desafio 1

Gerar um array aleatório de 100 elementos. Calcular a mediana correspondente.

In [1]:
import numpy as np
np_random = np.random.randint(100, size = 100)
np_random

array([30, 51, 76, 29, 58, 10, 15, 93, 28, 41, 80, 21, 70, 75, 40, 34, 69,
       72, 39, 20, 81,  9, 32, 75, 14, 63, 70, 27, 17, 53, 40, 19,  0, 87,
       32, 55, 91, 46,  5, 55, 50, 87, 50, 17, 43, 45, 17, 67, 36, 67, 55,
       99, 80, 74, 24, 20, 79, 24, 84,  5, 58, 19, 40,  1, 82, 91, 80, 73,
       20, 58, 68, 19, 88, 26, 13, 25, 46, 17, 26, 86, 22,  6, 49, 34, 76,
       67, 43, 96, 77, 65, 28, 53, 31, 13, 63, 80, 10, 54, 53, 78])

In [2]:
np.median(np_random)

47.5

# Desafio 2

Relembrar os exercícios com funções para cálculo de fatorial e soma de séries da Aula 02. Repetir os dois exercícios, mas agora utilizar as novas operações aprendidas com os ndarrays.

Desafio 1 - Escrever uma função para calcular o fatorial de um número qualquer.

In [3]:
n = int(input('Insira o número do fatorial que deseja calcular: '))
np_fat = np.arange(1, n + 1)
print(np_fat)
np.prod(np_fat)

Insira o número do fatorial que deseja calcular:  5


[1 2 3 4 5]


120

In [5]:
n = int(input('Insira o número do fatorial que deseja calcular: '))
np_fat = np.arange(1, n + 1)
np.prod(np_fat)

Insira o número do fatorial que deseja calcular:  3


6

Desafio 2 - Escrever uma função para calcular a soma de uma série começando por um número qualquer e terminando em outro número que deve ser maior que o primeiro.

In [6]:
n_inicial = int(input('Insira o número inicial da série: '))
print('LEMBRE-SE: O número final da série deve ser maior que o incial!')
n_final = int(input('Insira o número final da série: '))
np_soma_serie = np.arange(n_inicial, n_final + 1)
print(np_soma_serie)
np.sum(np_soma_serie)

Insira o número inicial da série:  1


LEMBRE-SE: O número final da série deve ser maior que o incial!


Insira o número final da série:  5


[1 2 3 4 5]


15

In [7]:
n_inicial = int(input('Insira o número inicial da série: '))
print('LEMBRE-SE: O número final da série deve ser maior que o incial!')
n_final = int(input('Insira o número final da série: '))
np_soma_serie = np.arange(n_inicial, n_final + 1)
print(np_soma_serie)
np.sum(np_soma_serie)

Insira o número inicial da série:  2


LEMBRE-SE: O número final da série deve ser maior que o incial!


Insira o número final da série:  4


[2 3 4]


9